swagger: "2.0"
info:
  title: "Launcher API"
  version: "1.0.0"
  description: "Authorization endpoint for Minecraft launcher"
host: "https://test.mtechlab.dev"
basePath: "/api"
schemes:
  - "https"
paths:
  /launcher/auth:
    post:
      tags:
        - "launcher"
      summary: "Login with launcher credentials"
      description: "Checks user credentials and returns JWT + UUID"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: credentials
          required: true
          schema:
            type: object
            required:
              - login
              - password
            properties:
              login:
                type: string
                example: "Steve"
              password:
                type: string
                example: "1234"
      responses:
        200:
          description: "Login result (success or error)"
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              result:
                type: object
                properties:
                  username:
                    type: string
                    example: "Steve"
                  userUUID:
                    type: string
                    example: "a85d44ce-bc33-402a-98c6-ce1e1b490781"
                  accessToken:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
              error:
                type: string
                example: "Invalid login or password"
